database:
  host: localhost
  port: 5432
  username: admin
  password: plaintext_password_123
  ssl: false

api_keys:
  openai_key: "sk-1234567890abcdef1234567890abcdef1234567890abcdef"
  stripe_key: "sk_test_51234567890abcdef1234567890abcdef"

security:
  jwt_secret: "my-super-secret-jwt-key"
  encryption: false
  verify_ssl: false
  
logging:
  level: debug
  file: "/var/log/app.log"
